name: test config
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install kind
        uses: helm/kind-action@v1.3.0
        with:
          config: config-simple.yaml
          version:

      - name: install helm
        uses: azure/setup-helm@v3

      - name: Test
        run: |
          kubectl get nodes
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install my-release bitnami/nginx
          kubectl wait deployment --all --for=condition=available --timeout=120s

      - name: Install failed, show platform logs
        if: ${{ failure() }}
        run: |
          kubectl get pods | awk '{print $1}' | xargs -n1 kubectl logs

      - name: Run Sanity check
        timeout-minutes: 5
        run: |
          kubectl apply -n default -f https://raw.githubusercontent.com/istio/istio/release-1.11/samples/bookinfo/platform/kube/bookinfo.yaml
          kubectl apply -n default -f examples/kubernetes/servicemesh/basic-ingress.yaml
          kubectl wait -n default --for=condition=Ready --all pod --timeout=${{ env.timeout }}

          lb=$(kubectl get ingress basic-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          curl -s -v --connect-timeout 5 --max-time 20 --retry 3 --fail -- http://"$lb"
          curl -s -v --connect-timeout 5 --max-time 20 --retry 3 --fail -- http://"$lb"/details/1