name: test config-simple
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install kind
        uses: helm/kind-action@v1.3.0
        with:
          config: config.yaml
          version:

      - name: Install helm
        uses: azure/setup-helm@v3

      - name: Test
        run: |
          kubectl get nodes
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install my-release bitnami/nginx
          kubectl wait deployment --all --for=condition=available --timeout=240s
          kubectl get svc
          kubectl get pod

      - name: Install failed, show platform logs
        if: ${{ failure() }}
        run: |
          kubectl get pods | awk '{print $1}' | xargs -n1 kubectl logs
